### ISSUE TITLE
Error in Backend after choosing custom template

### ISSUE THREAD

**Issue by Kahmoon** [heimrichhannot/contao-teaser-bundle#5] opened 2020-01-20 13:57 UTC
I get a contao error when i choose i custom template. Even when i set it back to default contao won´t find the template (it exists for sure) :-). 

> Internal Server Error
> Was ist das Problem?
> Could not find template "linkteaser_content_image_jbz"

It also happens when i change it back to default template. Frontend has no problem.

To reset this error i have to remove the template setting out of the database! :(

Stack Trace from Debug Mode

> Could not find template "linkteaser_content_image_jbz"

  at vendor/contao/core-bundle/src/Resources/contao/library/Contao/TemplateLoader.php:161
  at Contao\TemplateLoader::getDefaultPath('linkteaser_content_image_jbz', 'html5')
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/TemplateLoader.php:117)
  at Contao\TemplateLoader::getPath('linkteaser_content_image_jbz', 'html5')
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Controller.php:76)
  at Contao\Controller::getTemplate('linkteaser_content_image_jbz')
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/TemplateInheritance.php:324)
  at Contao\Template->getTemplatePath('linkteaser_content_image_jbz', 'html5')
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/TemplateInheritance.php:87)
  at Contao\Template->inherit()
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Template.php:286)
  at Contao\Template->parse()
     (vendor/contao/core-bundle/src/Resources/contao/classes/FrontendTemplate.php:44)
  at Contao\FrontendTemplate->parse()
     (vendor/heimrichhannot/contao-teaser-bundle/src/ContentElement/LinkTeaserElement.php:191)
  at HeimrichHannot\ContaoTeaserBundle\ContentElement\LinkTeaserElement->generateContent()
     (vendor/heimrichhannot/contao-teaser-bundle/src/ContentElement/LinkTeaserElement.php:140)
  at HeimrichHannot\ContaoTeaserBundle\ContentElement\LinkTeaserElement->generateLink()
     (vendor/heimrichhannot/contao-teaser-bundle/src/ContentElement/LinkTeaserElement.php:62)
  at HeimrichHannot\ContaoTeaserBundle\ContentElement\LinkTeaserElement->compile()
     (vendor/contao/core-bundle/src/Resources/contao/elements/ContentElement.php:247)
  at Contao\ContentElement->generate()
     (vendor/contao/core-bundle/src/Resources/contao/elements/ContentAlias.php:64)
  at Contao\ContentAlias->generate()
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Controller.php:545)
  at Contao\Controller::getContentElement(object(ContentModel))
     (vendor/contao/core-bundle/src/Resources/contao/dca/tl_content.php:1203)
  at tl_content->addCteType(array('id' => '162', 'pid' => '3', 'sorting' => '320', 'tstamp' => '1289249282', 'invisible' => '', 'type' => 'alias', 'headline' => '', 'text' => null, 'addImage' => '', 'singleSRC' => null, 'alt' => '', 'size' => '', 'imagemargin' => '', 'imageUrl' => '', 'fullsize' => '', 'caption' => '', 'floating' => '', 'html' => null, 'listtype' => '', 'listitems' => null, 'tableitems' => null, 'summary' => '', 'thead' => '', 'tfoot' => '', 'sortable' => '', 'sortIndex' => '0', 'sortOrder' => 'ascending', 'mooHeadline' => '', 'mooStyle' => '', 'mooClasses' => '', 'playerCaption' => '', 'highlight' => '', 'code' => null, 'url' => '', 'target' => '', 'linkTitle' => '', 'embed' => '', 'rel' => '', 'useImage' => '', 'multiSRC' => null, 'useHomeDir' => '', 'perRow' => '4', 'perPage' => '0', 'sortBy' => '', 'galleryTpl' => '', 'cteAlias' => '87', 'articleAlias' => '0', 'article' => '0', 'form' => '0', 'module' => '0', 'protected' => '', 'groups' => null, 'guests' => '', 'cssID' => 'a:2:{i:0;s:0:&quot;&quot;;i:1;s:9:&quot;teaserbox&quot;;}', 'playerColor' => 'a:2:{i:0;s:0:&quot;&quot;;i:1;s:0:&quot;&quot;;}', 'tleft' => '', 'imageTitle' => '', 'numberOfItems' => '0', 'ptable' => '', 'titleText' => '', 'orderSRC' => null, 'playerSRC' => null, 'youtube' => '', 'posterSRC' => null, 'playerSize' => '', 'start' => '', 'stop' => '', 'sliderDelay' => '0', 'sliderSpeed' => '300', 'sliderStartSlide' => '0', 'sliderContinuous' => '', 'customTpl' => '', 'metaIgnore' => '', 'bootstrap_dataAttributes' => null, 'overwriteMeta' => '', 'youtubeOptions' => null, 'overwriteLink' => '', 'playerOptions' => null, 'vimeoOptions' => null, 'playerStart' => '0', 'playerStop' => '0', 'glossarShowTagsDetails' => '', 'glossarShowTags' => '', 'termAsHeadline' => '', 'showAfterChoose' => '', 'addOnlyTrueLinks' => '', 'paginationPosition' => 'after', 'addNumericPagination' => '', 'addAlphaPagination' => '', 'headlineUnit' => '', 'sortGlossarBy' => '', 'glossar' => '', 'bs_image_sizes' => null, 'bs_grid_parent' => '0', 'bs_grid_name' => '', 'bs_grid' => '0', 'playerPreload' => '', 'playerAspect' => '', 'vimeo' => '', 'inline' => '', 'com_template' => '', 'com_requireLogin' => '', 'com_disableCaptcha' => '', 'com_bbcode' => '', 'com_moderate' => '', 'com_perPage' => '0', 'com_order' => '', 'teaserContentTemplate' => '', 'teaserLinkBehaviour' => '', 'teaserLinkCssClass' => '', 'teaserLinkText' => '', 'articleId' => '0', 'fileSRC' => null, 'jumpTo' => '0', 'source' => '', 'splashImage' => ''))
     (vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php:4569)
  at Contao\DC_Table->parentView()
     (vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php:360)
  at Contao\DC_Table->showAll()
     (vendor/contao/core-bundle/src/Resources/contao/classes/Backend.php:630)
  at Contao\Backend->getBackendModule('article', null)
     (vendor/contao/core-bundle/src/Resources/contao/controllers/BackendMain.php:161)
  at Contao\BackendMain->run()
     (vendor/contao/core-bundle/src/Controller/BackendController.php:50)
  at Contao\CoreBundle\Controller\BackendController->mainAction()
     (vendor/symfony/http-kernel/HttpKernel.php:151)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:68)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:198)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (web/index.php:31)

VG

**Comment by koertho** [comment] 2020-01-20 14:15
@Kahmoon Do you mean the Overwrite teaser template field? Which contao version are you using?

**Comment by Kahmoon** [comment] 2020-01-20 14:19
Yes, this field

Sorry....
Contao: 4.8.7
Module: contao-teaser-bundle 0.3.2

**Comment by koertho** [comment] 2020-01-20 15:51
@Kahmoon I think it's just a caching problem. I just tried it in an Contao 4.8 instance and got this error once, but not after clearing the cache. Please consider, that the dev and production cache must be cleared seperatly.
BTW: We already have a version 1.0 of this bundle.

**Comment by Kahmoon** [comment] 2020-01-21 08:36
Hmm i did clear the cache several times.

But i will try the new version of this module. Didn´t know there is a 1.*

**Comment by Kahmoon** [comment] 2020-01-21 08:50
I just installed 1.0.0. After that i changed the teaser element template from default to custom. Saving is ok. When i go to content element overview of my article 8which contains several teaser) the same error appears again:

Could not find template "linkteaser_content_image_jbz"

Clearing the cache via Contao Manager several times did not solve the problem. 

When i go back in history, which is the only way to avoid this error, and change the elements template back to default. The error is gone.

**Comment by koertho** [comment] 2020-01-21 13:05
Sorry, I can't reproduce this error. And it is really strange, since the template handling is done by contao and not some custom implementation. 
Do you have the template in the template folder of contao or in some vendor bundle?

**Comment by Kahmoon** [comment] 2020-01-21 13:33
Theme settings are Template folder: /jbz

The template is inside this folder. I can choose it in options and frontend also accepts it.

**Comment by koertho** [comment] 2020-01-22 08:06
Hello again, the problem was specific when the template was within an theme folder within the templates folder, since this is only working in frontend. This is fixed now in 1.0.1. Thanks for reporting!

**Closed by koertho** 2020-01-22 08:06 UTC

**Comment by Kahmoon** [comment] 2020-01-22 08:35
ahh sounds plausible :D. Thx
